### ISSUE TITLE
error when setting up predix space 

### ISSUE THREAD

**Issue by oudsteyn** [PredixDev/minds-machines-sf#5]
files_helper_funcs.sh not found when running quick start initialization script
$ ./scripts/quickstart-initialize-space-uaa-timeseries.sh

error produced
./local-setup-funcs.sh: line 170: bash/scripts/files_helper_funcs.sh: No such file or directory

**Comment by omerelhiraikage** [comment]
I managed to replicate the error produced, deleting the _'minds-machines-sf/predix-scripts'_ (an empty folder) should resolve this issue. The repo has been updated to remove this directory.

**Comment by oudsteyn** [comment]
That fixed it - Thanks
